# Generated by Django 3.2.18 on 2023-05-22 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egotype_name', models.CharField(max_length=100)),
                ('genres', models.ManyToManyField(to='tmdb.Genre')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EgoTypeCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility', models.TextField()),
                ('ego_type_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities_a', to='ego.egotype')),
                ('ego_type_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities_b', to='ego.egotype')),
            ],
        ),
    ]
