# Generated by Django 3.2.18 on 2023-05-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ego', '0002_egotype_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egotype',
            name='egotype_content',
        ),
    ]
