# Generated by Django 3.2.18 on 2023-05-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0002_auto_20230520_1628'),
        ('egoexpand', '0002_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option1_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option1_questions', to='tmdb.actor'),
        ),
        migrations.AddField(
            model_name='question',
            name='option1_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option1_questions', to='tmdb.genre'),
        ),
        migrations.AddField(
            model_name='question',
            name='option1_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option1_questions', to='tmdb.movie'),
        ),
        migrations.AddField(
            model_name='question',
            name='option2_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option2_questions', to='tmdb.actor'),
        ),
        migrations.AddField(
            model_name='question',
            name='option2_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option2_questions', to='tmdb.genre'),
        ),
        migrations.AddField(
            model_name='question',
            name='option2_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option2_questions', to='tmdb.movie'),
        ),
        migrations.AddField(
            model_name='question',
            name='option3_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option3_questions', to='tmdb.actor'),
        ),
        migrations.AddField(
            model_name='question',
            name='option3_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option3_questions', to='tmdb.genre'),
        ),
        migrations.AddField(
            model_name='question',
            name='option3_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option3_questions', to='tmdb.movie'),
        ),
        migrations.AddField(
            model_name='question',
            name='option4_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option4_questions', to='tmdb.actor'),
        ),
        migrations.AddField(
            model_name='question',
            name='option4_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option4_questions', to='tmdb.genre'),
        ),
        migrations.AddField(
            model_name='question',
            name='option4_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option4_questions', to='tmdb.movie'),
        ),
    ]
