# Generated by Django 3.2.18 on 2023-05-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egoexpand', '0003_auto_20230520_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genrequestion',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genrequestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='moviequestion',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='moviequestion',
            name='question',
        ),
        migrations.DeleteModel(
            name='ActorQuestion',
        ),
        migrations.DeleteModel(
            name='GenreQuestion',
        ),
        migrations.DeleteModel(
            name='MovieQuestion',
        ),
    ]
