# Generated by Django 3.2.18 on 2023-05-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egoexpand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
    ]
